###
POST http://localhost:3003/

Content-Type: application/json
{
    "title": "Frango desfiado",
    "description": "Pegar um peito de frango e desfiar"
}

###
POST  http://localhost:3003/user/signup
Content-Type:  application/json

{
	"name": "Alice",
	"email": "alice@lbn.com",
	"password": "123456"
}