###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Hilario",
    "email": "hilario@fonceca.com",
    "password": "hilariofonceca"
}


###
GET  http://localhost:3003/users

###
POST http://localhost:3003/products
Content-Type:  application/json

{
    "name": "Viagem para o meio do oceano para entender as dificuldades das Grandes Navegações",
    "price": 2800,
    "image": "https://picsum.photos/id/1041/5184/2916"
}

###
GET  http://localhost:3003/products

###
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "6cfd3c7e-c15e-4dd9-a07b-823ab232ca9a",
    "productId": "6f62ace1-f0d7-44f1-9f75-e942f473b1f3",
    "quantity": 3
}

###
GET http://localhost:3003/users/6cfd3c7e-c15e-4dd9-a07b-823ab232ca9a/purchases
